POST https://surrealcaptionformat.now.sh/removebracketsandcheckimageurl
Content-Type: application/json

{
    "title":"{{Title}} by {{Author}}",
    "imgurl":" https://cdn.pixabay.com/photo/2019/06/28/20/22/bridge-4304946_960_720.jpg",
    "url":" {{PostURL}}",
    "callbackurl":"https://maker.ifttt.com/trigger/tumblrpost/with/key/b5itM9wv5C8f-6ovk-On7p"
}